org.gradle.jvmargs=-Xmx2G -Djdk.tls.client.ciphers=TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 -Djdk.tls.client.enableSessionTicketExtension=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.java.installations.paths=/Users/huangwenqin/jdks/amazon-corretto-25.jdk/Contents/Home
org.gradle.java.home=/Users/huangwenqin/jdks/amazon-corretto-25.jdk/Contents/Home

# 版本（对齐本机已有的 Fabric 构建缓存）
minecraft_version=26.2
loader_version=0.19.3
fabric_api_version=0.154.2+26.2
modmenu_version=20.0.1

# 模组信息
mod_version=1.0.0
maven_group=com.custommusic
archives_base_name=custom-music
